MAIN = Connect4Game

default: cpsc2150/connectx/*.java
	javac cpsc2150/connectx/Connect4Game.java

run: cpsc2150/connectx/*.java
	java cpsc2150.connectx.Connect4Game

clean: cpsc2150/connectx/*.class
	rm -f *.class
