default: cpsc2150/myQueue/*.java
	javac cpsc2150/myQueue/IntegerQueueApp.java
	javac cpsc2150/myQueue/StringQueueApp.java

runInt: cpsc2150/myQueue/*.class
	java cpsc2150.myQueue.IntegerQueueApp

runString: cpsc2150/myQueue/*.class
	java cpsc2150.myQueue.StringQueueApp

clean: cpsc2150/myQueue/*.class
	rm -f *.class
