default: cpsc2150/connectX/*.java
	javac cpsc2150/connectX/Connect4Game.java 
    
run: cpsc2150/connectX/*.java
	java cpsc2150.connectX.Connect4Game

test: cpsc2150/connectX/*.java
	javac -cp .:/usr/share/java/junit4.jar cpsc2150/connectX/TestIGameBoard.java
runtest: cpsc2150/connectX/*.java
	java -cp .:/usr/share/java/junit4.jar org.junit.runner.JUnitCore cpsc2150.connectX.TestIGameBoard
