CREATE TABLE BASE_PRICE(
    PRICE_ID INTEGER(10) NOT NULL,
    PRICE DOUBLE NOT NULL,
    CRUST_TYPE VARCHAR(30) NOT NULL,
    PIZZA_SIZE INTEGER(2) NOT NULL,
    BASE_COST DOUBLE NOT NULL,
    PRIMARY KEY (PRICE_ID)
);
CREATE TABLE TOPPINGS(
    T_NAME VARCHAR(30) NOT NULL,
    PRICE_TO_CUSTOMER DOUBLE NOT NULL,
    COST_TO_BUSINESS DOUBLE NOT NULL,
    INVENTORY_LEVEL INTEGER(3),
    P_SMALL DOUBLE,
    P_MEDIUM DOUBLE,
    P_LARGE DOUBLE,
    P_X_LARGE DOUBLE,
    PRIMARY KEY (T_NAME)
);
CREATE TABLE ORDERS(
    ORDER_ID INT NOT NULL,
    PRIMARY KEY (ORDER_ID)
);
CREATE TABLE PIZZA(
    PIZZA_ID INTEGER NOT NULL,
    ORDER_STATUS VARCHAR(40),
    TIME_STAMP TIMESTAMP,
    P_PRICE_ID INTEGER(10) NOT NULL,
    P_ORDER_ID INTEGER(10) NOT NULL,
    CUSTOMER_PRICE DOUBLE NOT NULL,
    BUSINESS_COST DOUBLE NOT NULL,
    PRIMARY KEY (PIZZA_ID),
    FOREIGN KEY (P_ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (P_PRICE_ID) REFERENCES BASE_PRICE(PRICE_ID)
);
CREATE TABLE HAS_TOPPINGS(
    PIZZA_ID INT NOT NULL,
    TOPPING_NAME VARCHAR(30) NOT NULL,
    DOUBLE_AMOUNT INTEGER(2),
    PRIMARY KEY (PIZZA_ID, TOPPING_NAME),
    FOREIGN KEY (TOPPING_NAME) REFERENCES TOPPINGS(T_NAME)
);
CREATE TABLE DISCOUNTS(
    DISCOUNT_ID INTEGER(10) NOT NULL,
    NAME VARCHAR(50),
    DOLLAR_AMOUNT_OFF DOUBLE,
    PERCENTAGE_OFF DOUBLE,
    PRIMARY KEY (DISCOUNT_ID)
);
CREATE TABLE PIZZA_DISCOUNTS(
    P_PIZZA_ID INTEGER(10) NOT NULL,
    P_DISCOUNT_ID INTEGER(10) NOT NULL,
    PRIMARY KEY (P_PIZZA_ID, P_DISCOUNT_ID),
    FOREIGN KEY (P_PIZZA_ID) REFERENCES PIZZA(PIZZA_ID),
    FOREIGN KEY (P_DISCOUNT_ID) REFERENCES DISCOUNTS(DISCOUNT_ID)
);
CREATE TABLE ORDER_DISCOUNTS(
    O_ORDER_ID INTEGER(10) NOT NULL,
    O_DISCOUNT_ID INTEGER(10) NOT NULL,
    PRIMARY KEY (O_ORDER_ID, O_DISCOUNT_ID),
    FOREIGN KEY (O_ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (O_DISCOUNT_ID) REFERENCES DISCOUNTS(DISCOUNT_ID)
);
CREATE TABLE CUSTOMER(
    CUSTOMER_ID INTEGER(10) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(100),
    PHONE_NUMBER INTEGER(10),
    PRIMARY KEY (CUSTOMER_ID)
);
CREATE TABLE DINE_IN(
    ORDER_ID INTEGER(10) NOT NULL,
    TABLE_NUMBER INTEGER(2),
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);
CREATE TABLE SEAT_NUMBER(
    T_ORDER_ID INTEGER(10) NOT NULL,
    SEAT_NUMBER INTEGER(2) NOT NULL,
    PRIMARY KEY (T_ORDER_ID, SEAT_NUMBER),
    FOREIGN KEY (T_ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);
CREATE TABLE DELIVERY(
    D_ORDER_ID INTEGER(10) NOT NULL,
    CUSTOMER_ID INTEGER(10) NOT NULL,
    PRIMARY KEY (D_ORDER_ID),
    FOREIGN KEY (D_ORDER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);
CREATE TABLE PICK_UP(
    P_ORDER_ID INTEGER(10) NOT NULL,
    CUSTOMER_ID INTEGER(10) NOT NULL,
    PRIMARY KEY (P_ORDER_ID),
    FOREIGN KEY (P_ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);