CREATE TABLE BASE_PRICE(
    PRICE_ID INT NOT NULL,
    PRICE DOUBLE NOT NULL,
    CRUST_TYPE VARCHAR(30) NOT NULL,
    PIZZA_SIZE INT NOT NULL,
    BASE_COST DOUBLE NOT NULL,
    PRIMARY KEY (PRICE_ID)
);
CREATE TABLE TOPPINGS(
    NAME VARCHAR(30) NOT NULL,
    PRICE_TO_CUSTOMER DOUBLE NOT NULL,
    COST_TO_BUSINESS DOUBLE NOT NULL,
    INVENTORY_LEVEL INT,
    SMALL INT,
    MEDIUM INT,
    LARGE INT,
    X-LARGE INT,
    PRIMARY KEY (NAME)
);
CREATE TABLE ORDERS(
    ORDER_ID INT NOT NULL,
    PRIMARY KEY (ORDER_ID)
);
CREATE TABLE PIZZA(
    PIZZA_ID INT NOT NULL,
    ORDER_STATUS VARCHAR(40),
    TIME_STAMP TIMESTAMP,
    PRICE_ID INT NOT NULL,
    ORDER_ID INT NOT NULL,
    CUSTOMER_PRICE DOUBLE NOT NULL,
    BUSINESS_COST DOUBLE NOT NULL,
    PRIMARY KEY (PIZZA_ID),
    FOREIGN KEY ORDER_ID REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY PRICE_ID REFERENCES BASE_PRICE(PRICE_ID)
);
CREATE TABLE HAS TOPPINGS(
    PIZZA_ID INT NOT NULL,
    TOPPING_NAME VARCHAR(30) NOT NULL,
    DOUBLE TINYINT DEFAULT FALSE,
    PRIMARY KEY (PIZZA_ID, TOPPING_NAME),
    FOREIGN KEY TOPPING_NAME REFERENCES TOPPINGS(NAME)
);
CREATE TABLE DISCOUNTS(
    DISCOUNT_ID INT NOT NULL,
    NAME VARCHAR(50),
    DOLLAR_AMOUNT_OFF DOUBLE,
    PERCENTAGE_OFF DOUBLE,
    PRIMARY KEY (DISCOUNT_ID)
);
CREATE TABLE PIZZA_DISCOUNTS(
    PIZZA_ID INT NOT NULL,
    DISCOUNT_ID INT NOT NULL,
    PRIMARY KEY (PIZZA_ID, DISCOUNT_ID),
    FOREIGN KEY PIZZA_ID REFERENCES PIZZA(PIZZA_ID),
    FOREIGN KEY DISCOUNT_ID REFERENCES DISCOUNTS(DISCOUNT_ID)
);
CREATE TABLE ORDER_DISCOUNTS(
    ORDER_ID INT NOT NULL,
    DISCOUNT_ID INT NOT NULL,
    PRIMARY KEY (ORDER_ID, DISCOUNT_ID),
    FOREIGN KEY ORDER_ID REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY DISCOUNT_ID REFERENCES DISCOUNT(DISCOUNT_ID)
);
CREATE TABLE CUSTOMER(
    CUSTOMER_ID INT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(100),
    PHONE_NUMBER INT,
    PRIMARY KEY (CUSTOMER_ID)
);
CREATE TABLE DINE_IN(
    ORDER_ID INT NOT NULL,
    TABLE_NUMBER INT,
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);
CREATE TABLE SEAT_NUMBER(
    ORDER_ID INT NOT NULL,
    SEAT_NUMBER INT NOT NULL,
    PRIMARY KEY (ORDER_ID, SEAT_NUMBER),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
);
CREATE TABLE DELIVERY(
    ORDER_ID INT NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);
CREATE TABLE PICK_UP(
    ORDER_ID INT NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);