CREATE TABLE BASE_PRICE(
    PRICE_ID INT NOT NULL,
    PRICE DOUBLE NOT NULL,
    CRUST_TYPE VARCHAR(30) NOT NULL,
    PIZZA_SIZE INT NOT NULL,
    BASE_COST DOUBLE NOT NULL,
    PRIMARY KEY (PRICE_ID)
);
CREATE TABLE TOPPINGS(
    NAME VARCHAR(30) NOT NULL,
    PRICE_TO_CUSTOMER DOUBLE NOT NULL,
    COST_TO_BUSINESS DOUBLE NOT NULL,
    INVENTORY_LEVEL INT,
    SMALL TINYINT DEFAULT FALSE,
    MEDIUM TINYINT DEFAULT FALSE,
    LARGE TINYINT DEFAULT FALSE,
    PRIMARY KEY (NAME)
);
CREATE TABLE ORDERS(
    ORDER_ID INT NOT NULL,
    PRIMARY KEY (ORDER_ID)
);
CREATE TABLE PIZZA(
    PIZZA_ID INT NOT NULL,
    ORDER_STATUS VARCHAR(40),
    TIME_STAMP TIMESTAMP,
    PRICE_ID INT NOT NULL,
    ORDER_ID INT NOT NULL,
    CUSTOMER_PRICE DOUBLE NOT NULL,
    BUSINESS_COST DOUBLE NOT NULL,
    PRIMARY KEY (PIZZA_ID),
    FOREIGN KEY ORDER_ID REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY PRICE_ID REFERENCES BASE_PRICE(PRICE_ID)
);
CREATE TABLE HAS TOPPINGS(
    PIZZA_ID INT NOT NULL,
    TOPPING_NAME VARCHAR(30) NOT NULL,
    DOUBLE TINYINT DEFAULT FALSE,
    PRIMARY KEY (PIZZA_ID, TOPPING_NAME),
    FOREIGN KEY TOPPING_NAME REFERENCES TOPPINGS(NAME)
);
