CREATE TABLE SPONSOR (
    ID VARCHAR(10) NOT NULL,
    NAME VARCHAR(50),
    USERNAME VARCHAR(50),
    PASSWORD VARCHAR(25),
    EMAIL VARCHAR(50),
    PRIMARY KEY (ID)
);

CREATE TABLE MARKETPLACE (
    ID VARCHAR(10) NOT NULL,
    SPONSOR VARCHAR(30),
    PRIMARY KEY (ID)
);

CREATE TABLE ADMINISTRATIVE (
    ID VARCHAR(10) NOT NULL,
    NAME VARCHAR(50),
    USERNAME VARCHAR(50),
    PASSWORD VARCHAR(25),
    EMAIL VARCHAR(50),
    PRIMARY KEY (ID)
);

CREATE TABLE DRIVER (
    ID VARCHAR(10) NOT NULL,
    NAME VARCHAR(50),
    USERNAME VARCHAR(50),
    PASSWORD VARCHAR(25),
    EMAIL VARCHAR(50),
    POINT_TOTAL INTEGER(4),
    ORDER_HISTORY VARCHAR(50),
    PRIMARY KEY (ID)
);

CREATE TABLE SPONSORED_BY (
    SPONSOR VARCHAR(10) NOT NULL,
    DRIVER VARCHAR(10) NOT NULL,
    PRIMARY KEY (SPONSOR, DRIVER),
    FOREIGN KEY (SPONSOR) REFERENCES SPONSOR(ID),
    FOREIGN KEY (DRIVER) REFERENCES DRIVER(ID)
);

CREATE TABLE CAN_VIEW (
    SPONSOR VARCHAR(10) NOT NULL,
    DRIVER VARCHAR(10) NOT NULL,
    MARKET VARCHAR(10) NOT NULL,
    PRIMARY KEY (SPONSOR, DRIVER, MARKET),
    FOREIGN KEY (SPONSOR) REFERENCES SPONSOR(ID),
    FOREIGN KEY (MARKET) REFERENCES MARKETPLACE(ID),
    FOREIGN KEY (DRIVER) REFERENCES DRIVER(ID)
);

CREATE TABLE CAN_MODIFY_SPONSOR (
    ADMIN VARCHAR(10) NOT NULL,
    SPONSOR VARCHAR(10) NOT NULL,
    PRIMARY KEY (ADMIN, SPONSOR),
    FOREIGN KEY (SPONSOR) REFERENCES SPONSOR(ID),
    FOREIGN KEY (ADMIN) REFERENCES ADMINISTRATIVE(ID)
);

CREATE TABLE CAN_MODIFY_DRIVER (
    ADMIN VARCHAR(10) NOT NULL,
    DRIVER VARCHAR(10) NOT NULL,
    PRIMARY KEY (ADMIN, DRIVER),
    FOREIGN KEY (DRIVER) REFERENCES DRIVER(ID),
    FOREIGN KEY (ADMIN) REFERENCES ADMINISTRATIVE(ID)
);

CREATE TABLE CAN_MODIFY_MARKETPLACE (
    ADMIN VARCHAR(10) NOT NULL,
    MARKET VARCHAR(10) NOT NULL,
    PRIMARY KEY (ADMIN, MARKET),
    FOREIGN KEY (MARKET) REFERENCES MARKETPLACE(ID),
    FOREIGN KEY (ADMIN) REFERENCES ADMINISTRATIVE(ID)
);

CREATE TABLE ADD_PRODUCTS (
    MARKET VARCHAR(10) NOT NULL,
    SPONSOR VARCHAR(10) NOT NULL,
    PRODUCT_LIST VARCHAR(500) NOT NULL,
    PRIMARY KEY (MARKET, SPONSOR),
    FOREIGN KEY (MARKET) REFERENCES MARKETPLACE(ID),
    FOREIGN KEY (SPONSOR) REFERENCES SPONSOR(ID)
);

CREATE TABLE PRODUCTS (
    MARKET VARCHAR(10) NOT NULL,
    PRODUCT VARCHAR(50) NOT NULL,
    PRIMARY KEY (MARKET, PRODUCT),
    FOREIGN KEY (MARKET) REFERENCES MARKETPLACE(ID)
);
