MAIN = Connect4Game

default: cpsc2150/connectX/*.java
	javac cpsc2150/connectX/Connect4Game.java

run: cpsc2150/connectX/*.java
	java cpsc2150.connectX.Connect4Game

clean: cpsc2150/connectX/*.class
	rm -f *.class
