MAIN = QueueApp

default: cpsc2150/MyQueue/*.java
	javac cpsc2150/MyQueue/IntegerQueueApp.java

run: cpsc2150/MyQueue/*.java
	java cpsc2150.MyQueue.IntegerQueueApp

clean: cpsc2150/MyQueue/*.class
	rm -f *.class
