

default: cpsc4910/project/*.java
	javac -cp ./lib/mysql-connector-java-5.1.42/mysql-connector-java-5.1.42-bin.jar:. cpsc4910/project/Sponsor.java
	
run: cpsc4910/project/*.class
	java -cp ./lib/mysql-connector-java-5.1.42/mysql-connector-java-5.1.42-bin.jar:. cpsc4910.project.Sponsor

clean: cpsc4910/project/*.class
	rm cpsc4910/project/*.class
